name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 8.x
      - name: Test
        run: dotnet test
